### ISSUE TITLE
"Software suffers from a different type of bit rot than data"

### ISSUE THREAD

**Issue by khinsen** [danielskatz/software-vs-data#12]
If you want to clear up rather than enhance the confusion between software and data, please don't use the term "bit rot" for anything else than issues related to the durability of physical storage. The term clearly suggests a form of decay in time, which is very different from what happens to software and to data stored in proprietary formats: they become unusable because people change their computing environments.

**Comment by danielskatz** [comment]
I first heard software bit rot in this context from @jameshowison, so I think the confusion is already there.  As I think about it, bit rot might not be the right term, however.  Do you have a better suggestion?

**Comment by khinsen** [comment]
I propose to remove that whole paragraph. It doesn't convey any useful message except to people who believe that there is a universal natural phenomenon called "bit rot".

What this paragraph does address (badly) is the issue of dependencies. But that problem is exactly the same for software and for data, so there is no point in discussing it in the context of differences.

**Comment by danielskatz** [comment]
As mentioned in #9, I think there is a valuable point here, but perhaps it is just one point, and the two statements should be combined.

**Comment by mhucka** [comment]
I started writing this comment to agree with the perspective put forward by @khinsen – that "bit rot" is usually intended to refer to data corruption or degradation (i.e., unintentional transformations introduced by hardware or communications events), and that while in a technical sense it can afflict either software or data, this is not the same as problems introduced by changes in software dependencies. Then, at the last moment, I decided to google "bit rot", and discovered that in fact, there's a [Wikipedia page about bit rot as software rot](https://en.wikipedia.org/wiki/Software_rot)! So, it seems this concept seems to be pretty established and probably _should_ be mentioned by name. However, it is essentially the same as problems due to changes in software dependencies, so I also agree with @danielskatz's idea of merging this with the other discussion of dependencies.

**Comment by khinsen** [comment]
Yes, the term bit rot has found some use in the sense we discuss, but that doesn't mean this is a good habit that we should perpetuate. If you want to solve a problem, or at least draw useful conclusions from its existence, misleading terms are an obstacle. Discussing the problem in the context of dependencies is much more helpful, so I am for that as well.

**Comment by danielskatz** [comment]
addressed by https://github.com/danielskatz/software-vs-data/commit/c62aed523ccc368d7508d7ea4de012ec2842c0d3
