### ISSUE TITLE
Introduction and the question: is software just a subset of data?

### ISSUE THREAD

**Issue by cboettig** [danielskatz/software-vs-data#3]
To many, the idea that software is different from data is as self-evident as, say, the idea that an academic paper is different from data.  Those of us who have been around data repository thinkers enough probably recognize the relevance of this question, but the greatest value of this piece might be instead in highlighting the importance of making a distinction at all.  (In other words, what opportunity is lost by declaring that software is simply data).

In the same vein, the data purist might claim with some justification that, while clearly not all data is software (handwritten observations, for instance), that software is just a special subset of data.   Few of the current points really refute this -- i.e. to give the devil's advocate position on the current points:
- much data is streaming, updating every second.  
- being executable may define what makes it software, but data isn't defined by being not-executable, any more than it's defined by being not-digital, etc.
- lots of different data suffers lots of different processes of information decay over time.  different types of bit rot are just a subset
- data is frequently used to build other data (voltage fluctuations in a piece of circutry are converted to instantaneous temperature measurements which are averaged over space and time into aggregate records etc)
- large teams creating data exist (particle physics comes to mind, among others)
- short-lived data exist

Many of these issues are perhaps more elegant critiques of the weaknesses of current scientific data repository mechanisms for archiving, attribution, discovery etc of some kinds of data than they are black-and-white differences in software.  Of course the crucial role of software means it may demand more attention addressing these problems (just as we build infastructure to support "big data" without claiming all data is "big".)

**Comment by khinsen** [comment]
I propose two steps towards reducing the confusion about the roles of software and data:
1. Insist on the context (i.e. citations in scientific work). It's already stated, but could be clearer.
2. Use a more specific term than "data" to describe what you want to discuss. The current arguments suggest that "data" means "raw observations recorded electronically". That's clearly different from software in my opinion.

Context matters because people approach this question from different perspectives. From the point of view of computational theory, software is data, and that's in fact a fundamental insight. From the point of view of computational science, the distinction becomes apparent but is still not clear.

There are many intermediates between software and recorded observations, and it would be good to say something about them as well. In particular, what about files containing processed observations? If the processing was done by a human ("data munging"), the result may be subject to copyright. If the processing was done by software, the result may change with the software and thus be subject to the same versioning issues. Consider for example a file containing the weights of a neural network trained on recorded observations. I'd say this is neither pure software nor pure observation.

**Comment by danielskatz** [comment]
I would appreciate it if you can make a pull request making these 2 changes/steps.

**Comment by roomthily** [comment]
Before getting down into data definition weeds (and some of what's been stated does not reflect definitions out of the data citation discussions, ie the source of the concerns, or data definitions in the broader, non-CS research communities), it is worth noting why there's a push for citing data, code, ontologies, etc. As citable objects, there's really not that much difference honestly, but there is reason to discuss software citation independently of data from an outreach and adoption perspective. rather than continuing with "what is data" debates that aren't productive, it might be worth considering revisions with that in mind.

Thanks.

**Comment by danielskatz** [comment]
I really don't think that "as citable objects, there's really not that much difference honestly" is correct.  This was the consensus of the Software Citation working group, and the reason that the software citation principles that have been generated are different than the data citation principles.  On the other hand, I do agree that these differences haven't been explained well and that there hasn't been much evidence assembled to show this, but that's the intended purpose of this document.

**Comment by roomthily** [comment]
So we cite datasets, not data. It is a meaningful distinction in a way any comparison between file sizes, rate of change, versioning, variety just won't be (and can be easily deflected with exceptions beyond what's added to date). That is also the bias in both the data citation and dynamic data citation documents. Worth noting. 

Also worth noting that we've had to define "dataset" non-stop for publication purposes (and thus citation purposes) and that those definitions are, often, context-dependent. We don't rely on context to define software in each little subdomain/domain. It's nice.

There has been no conversation last couple of years related to data, software, ontology/vocabulary citation that did not include the same core elements and the same motivation. Authorship, contributions, version, dereferencable URI (as DOI or otherwise), permanence, publication location, list of things related to that Thing at the end of that URI and all of that outside of differences in how we manage any one of them during its active life. It is the same conversation. Doesn't matter and doesn't deny the importance of citation for any one of those things.  Definitely does not change or minimize the importance of any one of those types of things in our research cultures or in the need for documents addressing that need for each type. That is audience and outreach. 

It is the awareness of how critical software (and code) is to how we do research and citations as a way of indicating that that matters. 

Would be a significant text change, probably.

**Comment by danielskatz** [comment]
Can you explain this a bit more, perhaps with some idea of the what changed text would look like?  I feel like I'm not really getting what you are saying.

**Comment by danielskatz** [comment]
I'm going to close this soon unless anyone wants to make an action (a PR) based on it.
