### ISSUE TITLE
Copyright on data

### ISSUE THREAD

**Issue by agbeltran** [danielskatz/software-vs-data#43]
In the current text, the section 'Software is a creative work, scientific data are facts or observations.' indicates 'scientific data is frequently considered outside the domain of copyright as it is comprised of contextual facts about the world (you cannot copyright the height of Mt. Everest.)'.

While I understand that this is correct and frequently data is factual, there are cases where data can be copyrighted, e.g. recordings of an interview in interview data (see evidence here: https://www.liverpool.ac.uk/csd/research-data-management/sharing/copyright/)

Other resources:
- [UK Data Service](https://www.ukdataservice.ac.uk/manage-data/rights): "Many kinds of data created as part of a research project are subject to the same rights as literary or artistic work."
- [Copyright and research data](http://researchdata.berkeley.edu/content/copyright-and-research-data) - describes the issues around data and copyright

I think that it would be useful in this comparison to take into account the cases where data can be considered a creative work, even though in most cases it would be representing facts about the world. I could suggest text changes if there is consensus about this addition.

Also, the text refers to 'scientific data' and the resources I included refer to 'research data' but I guess that the comparison should be about data in general? Thanks.

**Comment by danielskatz** [comment]
The text used to say "Software is a creative work, data are facts or observations."

"Data" was changed to "scientific data"  - see https://github.com/danielskatz/software-vs-data/pull/35 - so that we didn't have to get into general data and could focus on scientific data.

If you a specific suggestion that you think would make things more clear and not more complex, please let me know.
